#:schema node_modules/wrangler/config-schema.json
name = "xiaolurenya-image"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".next/static"

[ai]
binding = "AI"

[[r2_buckets]]
bucket_name = "xiaolurenya-image"
binding = "BUCKET"

[vars]
CLOUDFLARE_ACCOUNT_ID = "57b41b7ddf3e05e5d93c1fd7fd818823"

[env.production]
name = "xiaolurenya-image"

[[env.production.r2_buckets]]
bucket_name = "xiaolurenya-image"
binding = "BUCKET"
